# 1. Habilita o filtro de CORS
quarkus.http.cors=true

# 2. Autoriza especificamente a origem que vimos no HAR
quarkus.http.cors.origins=http://127.0.0.1:5500,http://localhost:5500

# 3. Autoriza o header 'content-type' que o navegador solicitou 
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

# 4. Autoriza o método POST que está sendo usado [cite: 3]
quarkus.http.cors.methods=GET, POST, OPTIONS

quarkus.http.port=7000